export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_POPULAR_TV_SERIES = "GET_POPULAR_TV_SERIES";
